version: '2'
services:
  proxy:
    image: rdsubhas/tor-privoxy-alpine
  crawler:
    image: node:7.4
    volumes:
      - ./app:/usr/src/crawler/app
      - metadata:/usr/src/crawler/data
    working_dir: /usr/src/crawler/app
    command: node app.js --cron "0 10 0 * * 6" --run
    depends_on:
      - proxy
    environment:
      - http_proxy=http://proxy:8118/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    ports:
      - "9200:9200"
    volumes:
      # - elasticsearch_config:/usr/share/elasticsearch/config
      - elasticsearch_data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.0.0
    volumes:
      - ./logstash:/crawler/logstash
      - metadata:/crawler/data
    command: bash -c "env GEM_HOME=$$(echo /usr/share/logstash/vendor/bundle/jruby/*/) /opt/logstash/vendor/jruby/bin/jruby /opt/logstash/vendor/jruby/bin/gem install geocoder -v 1.4.4 && echo 'gem \"geocoder\", \"~> 1.4.4\"' >> /usr/share/logstash/Gemfile && logstash -f /crawler/logstash/metadata.conf"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    ports:
      - "5601:5601"
    # volumes:
    #  - kibana_config:/etc/kibana/
    depends_on:
      - elasticsearch
volumes:
  metadata: {}
  elasticsearch_data: {}
  # elasticsearch_config: {}
  # kibana_config: {}
